### ISSUE TITLE
Linix

### ISSUE THREAD

**Issue by Blackbear199** [harrygg/xmltv-tools#1]
Hi,
nice application you created.
i am testing this on a linux setup and it doesnt seem to find the WebGrab+Plus.exe
spelling is correct,debug shows it finding the config file(which is in the same directory).
i am only testing a single channel with a single ini for now.
i think the problem is its not starting the WebGrab+Plus.exe with mono?

#####################################################
#                                                   #
#        wgmulti for WebGrab++ by Harry_GG          #
#                                                   #
#####################################################

 System: Unix
 Arguments: None
 ConfigDir: /home/linux/Downloads/WebGrab+Plus
 MaxAsyncProcesses: 10
 GroupChannelsBySiteIni: True
 MaxChannelsInGroup: 5
 ConvertTimesToLocal: True
 ShowConsole: False

-----------------------------------------------------

Execution started at: 4/4/2017 10:25:42 AM
Loading configuration from /home/linux/Downloads/WebGrab+Plus/WebGrab++.config.xml
settings node loaded
"filename" value is set to "/home/linux/downloads/webgrab+plus/guide.xml"
filename set to /home/linux/downloads/webgrab+plus/guide.xml
"mode" value is set to "n"
"proxy" value not found! Using the default value ""
"user-agent" value is set to "mozilla/5.0 (x11; ubuntu; linux x86_64; rv:49.0) gecko/20100101 firefox/51.0"
"logging" value is set to "off"
"skip" value is set to "noskip"
"timespan" value is set to "0"
"update" value is set to "f"
"retry" value is set to "5"
"time-out" value is set to "30"
"channel-delay" value not found! Using the default value "5"
"index-delay" value not found! Using the default value "1"
"show-delay" value not found! Using the default value "1"
"postprocess" value is set to "mdb"
"run" value is set to "n"
"grab" value is set to "y"
Is postprocess enabled: False
Split channels into 1 groups
Creating config file in /tmp/wgmulti/horizon.tv/WebGrab++.config.xml
Grabber HORIZON.TV initialized
Starting grabbers asynchronously, 10 at a time
ERROR! WebGrab+Plus.exe not found and not executable!
wgmulti execution time: 00:00:00.13

**Comment by harrygg** [comment]
The Webgrab+Plus.exe must have executable priviledges, otherwise it won't be started:
I suggest you chmod both:
chmod +x WebGrab+Plus.exe
chmod +x wgmulti.exe

**Comment by Blackbear199** [comment]
thank you very much,that was the problem.
i used to chmod the WebGrab+Plus.exe all the time when using it on linux but found it worked ok without when running it with mono so i stopped doing it.I know this is a bad habit and my fault.
now i see another issue..
from my WebGrab++config.xml..
<filename>/home/linux/Downloads/WebGrab+Plus/guide.xml</filename>
when it reads this info its not getting the case sensitive..
"filename" value is set to "/home/mike/downloads/webgrab+plus/guide.xml"
so when it tries to merge its not finding it?
Merging single EPGs, master EPG will be saved in /home/linux/downloads/webgrab+plus/guide.xml
System.IO.DirectoryNotFoundException: Could not find a part of the path "/home/linux/downloads/webgrab+plus/guide.xml".
i could rename everything to be all lower case but shouldnt it detect the path from the WebGrab++config.xml correctly.
thanks.

**Comment by harrygg** [comment]
Thanks for you analysis.

I think the exe doesn't need to be executable if it's started like this:
"mono WebGrab+Plus.exe" 
However the tool uses the command "./WebGrab+Plus.exe <config-file>" to start webgrab, so it needs to be executable. Perhaps I can change the command...

Regarding the second issue, yes it should! But since this tool was developed and tested primarly on Windows I never noticed issues. 
I will see what I can change to fix it.

**Comment by harrygg** [comment]
Lowercase issue should be fixed now.

**Comment by Blackbear199** [comment]
thank you,works as expected now.this can be closed.
