### ISSUE TITLE
Multi Guide locations

### ISSUE THREAD

**Issue by unlocKing** [harrygg/xmltv-tools#2]
Hi,

This works fantastically with the default WebGrab locations. Amazing work, thanks. 👍 

I have a few guides running, how can I use this with other locations such us:

C:\EPG\Guide1
C:\EPG\Guide2
C:\EPG\Guide3

Currently I am using this command for WebGrab to start:

"C:\Program Files (x86)\ServerCare\WebGrab+PlusV1.1.1\WebGrab+Plus.exe" "C:\EPG\Guide1"

**Comment by Blackbear199** [comment]
i think your missing the point of what his application does.
rather than divide the grabs up like you have done,his application take all the channels in the webgrab++config.xml and grabs the using multiple instances of webgarb by ini or by group of x number of channels.
 to do this with the setup you have you would need to run 3 instances of his program.

**Comment by Blackbear199** [comment]
also when its all done you would still need to merge the 3 resulting xml files.

**Comment by harrygg** [comment]
Wgmulti accepts the same arguments as Webgrab. Any none-default location can be passed as argument i.e. 
wgmulti.exe <path-to-config-dir>

**Comment by unlocKing** [comment]
@Blackbear199 I'm running multiple guides for different apps, hence the setup.

@harrygg Thanks, will try that now.

Cheers!

**Comment by retrorat1** [comment]
Just running it now looks real good , Thanks

**Comment by unlocKing** [comment]
Keep seeing these errors:

Grabber UK-SKY.COM | ERROR! 128 error downloading page: The process cannot access the file 'C:\Users\j\AppData\Local\Temp\wgmulti\uk-sky.com\hot_cookies.txt' because it is being used by another process. (5sec)

and

Grabber UK-SKY.COM | ERROR! 133 error downloading page: The process cannot access the file 'C:\Users\j\AppData\Local\Temp\wgmulti\uk-sky.com\hot_cookies.txt' because it is being used by another process. (5sec)


Can something be done about that file being accessed?

**Comment by harrygg** [comment]
You are not running multiple instances of wgmulti, are you?
Can you give me a WG config with the least possible number of channels to reproduce the issue?

**Comment by retrorat1** [comment]
Didn't work fully for me,  
Split up config into 85 groups - Done
Downloaded grab and created epg.xml in each of the 85 folders - done
Combine all epg.xml files to one - not done
Combine all log files into one master log file - not done.
I used the same config file without changing anything but will go over it today as have more time.

**Comment by unlocKing** [comment]
No, just the one instance whilst testing..

In the end this was a much slower process.

Here's a log I grabbed from the screen.
[wgmulti-test.txt](https://github.com/harrygg/xmltv-tools/files/895585/wgmulti-test.txt)

**Comment by harrygg** [comment]
I made some changes that should fix the EPG and LOGs merging problem. 

But I am not sure what causes the issue with the hot_cookies.txt file...
I personally grab over 400 channels (33 come from uk-sky.com) and I don't get this issue. 

My overall grabbing time is 10 minutes. (Note that the first time you run the tool it will create EPGs from scratch and next time it will start incrementing hence it will be faster).

**Comment by unlocKing** [comment]
That is strange, I'll test the new version now and let you know.

Thanks dude.

**Comment by unlocKing** [comment]
Better this time around:

[wgmulti-test2.txt](https://github.com/harrygg/xmltv-tools/files/900198/wgmulti-test2.txt)
