### ISSUE TITLE
Can't get it working with WebGrab+Plus v2.1

### ISSUE THREAD

**Issue by DarrenScottkcc** [harrygg/xmltv-tools#4]
I don't know how to get this working with WebGrab+Plus v2.1. Can someone help me please

**Comment by DarrenScottkcc** [comment]
i fixed it. what i did was create a batch file and locate the WebGrab+Plus.exe and execute it

**Comment by PixieScr** [comment]
Help with this problem. DarrenScottkcc, upload batch file please

**Comment by kodibg** [comment]
I've never tested it with WG 2. I'll try it soon and let you know.

**Comment by harrygg** [comment]
I've never tested it with WG 2. I'll do it and let you know.

**Comment by PixieScr** [comment]
Thx

**Comment by PixieScr** [comment]
Any news ?

**Comment by harrygg** [comment]
I'm sorry I don't have time to test it. Maybe later this week...

**Comment by harrygg** [comment]
Hello,

I noticed the Webgrab default config location has changed to C:\Users\<username>\AppData\Local\WebGrab+Plus

Have you tried starting to the tool with the path to the config folder as an argument:
wgmulti.exe C:\Users\<username>\AppData\Local\WebGrab+Plus

**Comment by PixieScr** [comment]
I tried and its working, thx :)
