### ISSUE TITLE
Wgmulti on linux

### ISSUE THREAD

**Issue by Pancronos** [harrygg/xmltv-tools#5]
My wgmulti goes in error after loading webgrab++config. On ubuntu all the files and folders are in a folder called webgrabtest
ubuntu@ubuntu:~/Scrivania/webgrabtest$ mono wgmulti.exe
#####################################################
#                                                   #
#        wgmulti for WebGrab++ by Harry_GG          #
#                                                   #
#####################################################

 System: Unix
 Arguments: None
 ConfigDir: /home/ubuntu/Scrivania/webgrabtest/
 Build config from JSON file: True
 JsonConfigFileName: wgmulti.channels.json
 MaxAsyncProcesses: 15
 GroupChannelsBySiteIni: True
 MaxChannelsInGroup: 10
 ConvertTimesToLocal: True
 ShowConsole: True

-----------------------------------------------------

Execution started at: 07/09/2017 15:35:23
Loading configuration from /home/ubuntu/Scrivania/webgrabtest/WebGrab++.config.xml
settings node loaded
"filename" value is set to "/home/ubuntu/Scrivania/webgrabtest/test.xml"
filename set to /home/ubuntu/Scrivania/webgrabtest/test.xml
"mode" value is set to "m n"
"proxy" value is set to "automatic"
"user-agent" value is set to "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36"
"logging" value is set to "on"
"skip" value not found! Using the default value "noskip"
"timespan" value is set to "0"
"update" value is set to "f"
"retry" value is set to "2"
"time-out" value is set to "5"
"channel-delay" value not found! Using the default value "5"
"index-delay" value not found! Using the default value "1"
"show-delay" value not found! Using the default value "1"
"postprocess" value is set to "rex"
"run" value is set to "n"
"grab" value is set to "y"
Is postprocess enabled: False
Splitting channels into 1 groups
Grabber RAIPLAY.IT | ERROR | Ini file does not exist. Grabbing will be skipped!
/home/ubuntu/Scrivania/webgrabtest/raiplay.it.ini
No active grabbing created. Exiting!
ubuntu@ubuntu:~/Scrivania/webgrabtest$

The site ini is present in 2 subfolders of webgrabtest:  siteini.pack and siteini.user, so  it looks like is not looking in subfolders for the ini .

**Comment by harrygg** [comment]
I must have accidently commited an untested version. Please downgrade or set BuildConfigFromJSON to false.

**Comment by Pancronos** [comment]
set it like 
    <add key="BuildConfigFromJson" value="false" />    
but still no luck

**Comment by harrygg** [comment]
Please try the latest one I uploaded:
https://github.com/harrygg/xmltv-tools/tree/master/wgmulti/bin/Debug

**Comment by Pancronos** [comment]
Hello Harry, the one posted in Debug works ok. Unfortunately it looks like that if the post process is enabled (rex in my case) you get errors and then it crash:
`Grabber TBNUK.ORG.UK | Parsing XML output

Unhandled Exception:
System.IO.FileNotFoundException: Could not find file "/tmp/wgmulti/tbnuk.org.uk/epg.xml"
File name: '/tmp/wgmulti/tbnuk.org.uk/epg.xml'
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <8dab04c9e11049579ba5c8d3adeb8085>:0
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize) [0x00000] in <8dab04c9e11049579ba5c8d3adeb8085>:0
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)
`
This happens the first time you run. 
I tried to run without postprocess (all ok)  and the with incremental mode and postprocess enabled and it worked. I think it needs a little tune-up for the first time so postprocess doesn't look for something it has not been grabbed yet, at least that's what it looks like.

**Comment by harrygg** [comment]
Yes I am aware. This new version is still in development and I haven't tested the post process. 
There is a zip file in the Debug folder which contains the old version of wgmulti.exe and that one should work with post process enabled.

**Comment by Pancronos** [comment]
with the zip version and post process enabled don't get what is in siteini.user:
`ubuntu@ubuntu:~/Scrivania/webgrab$ mono wgmulti.exe
#####################################################
#                                                   #
#        wgmulti for WebGrab++ by Harry_GG          #
#                                                   #
#####################################################

wgmulti started on Unix
Arguments: None
Using config folder: /home/ubuntu/Scrivania/webgrab
Max WebGrab instances: 50
Convert programmes' times to local time: True
Show WebGrab+ UI: False

Execution started at: 09/09/2017 10:05:21
System.NullReferenceException: Object reference not set to an instance of an object
  at wgmulti.Config.GetChannels () [0x0007b] in <e93ead867da54b03baeba50f58fdbba2>:0
Splitting channels into groups according to siteini
60 grabbers will be created
Grabber GUIDATVMOD.SKY.IT | ERROR | Ini file does not exist. Grabbing will be skipped!
/home/ubuntu/Scrivania/webgrab/guidatvmod.sky.it.ini
`
it will also be good if you can add a version/revision number.

**Comment by Pancronos** [comment]
Working ok on latest release. Again suggest a wgmulti version be shown in log:
#################################################                                                                                                             
#      Wgmulti.exe for WebGrab+Plus by Harry_GG  Ver.1.0                                                                                                                 #################################################
