### ISSUE TITLE
time correct

### ISSUE THREAD

**Issue by ghost** [harrygg/xmltv-tools#6]
great work on your latest updates that added json file and post processors.

 i was wondering if the time correct could be made dynamic rather than convert to local only.
could another argument be added to specify the timezone one wants to convert to?

**Comment by timtimtim1** [comment]
I would like this too.

**Comment by harrygg** [comment]
That is possible in the latest version uploaded yesterday.
You need to specify "offset"property for any channel (not only for the time-shifted ones).

Be aware that there are minor changes in the syntax of the JSON config file (wgmulti.config.json) and the wgmulti runtime config (wgmulti.exe.config). The easiest way to generate a JSON config is to run wgmulti with your default WebGrabPlus XML config and it will automatically convert and export it to JSON config file. Then modify the JSON as needed save it as wgmulti.config.json and use it.

**Comment by harrygg** [comment]
Next feature in my road map is - different timespan for different siteinis.

**Comment by kroken123** [comment]
Thank you for promt reply! do you mean we have to add offset for each channel? i was thinking a parameter for this in wgmulti.exe.config where you can set another timezone rather than the local preconfigured already.

**Comment by harrygg** [comment]
Yes, currently you have to add it to each channel. 
But I am working on the next changes and I will include setting a global offset applicable to all channels, a local offset per siteini and offset per channel.

**Comment by kroken123** [comment]
Thank you harryygg! i have problem starting the tool in a shellscript, isnt this how you do it?

mono wgmulti.exe "/home/me/webgrabplus/"

**Comment by harrygg** [comment]
I usually "chmod +x wgmulti.exe" and then run directly "./wgmulti.exe <config-dir>", but make sure the correct entries are added to wgmulti.exe.config.

**Comment by kroken123** [comment]
yes i did, but i tried to run wgmulti.exe from another folder to load a different configuration but it looks like its not finding the config in /home/me/webgrabplus/

**Comment by harrygg** [comment]
I am not sure what you are doing :) Can you send me a wgmulti.log.txt to have a look. 
BTW, please open a new thread as one was opened for something else.
